CREATE TABLE IF NOT EXISTS `login` (
  `account_id` int(11) unsigned NOT NULL auto_increment,
  `userid` varchar(23) NOT NULL default '',
  `user_pass` varchar(100) NOT NULL default '',
  `email` varchar(39) NOT NULL default '',
  `character_slots` tinyint(3) unsigned NOT NULL default '4',
  `account_privilege` tinyint(3) NOT NULL default '0',
  `logincount` mediumint(9) unsigned NOT NULL default '0',
  `last_ip` varchar(100) NOT NULL default '',
  PRIMARY KEY  (`account_id`),
  KEY `name` (`userid`)
) ENGINE=MyISAM AUTO_INCREMENT=2000000;

CREATE TABLE IF NOT EXISTS `character` (
  `characterid` int(11) unsigned NOT NULL auto_increment,
  `account_id` int(11) unsigned NOT NULL default '0',
  `char_num` tinyint(1) NOT NULL default '0',
  `name` varchar(30) NOT NULL DEFAULT '',
  `level` smallint(6) unsigned NOT NULL default '1',
  `base_exp` bigint(20) unsigned NOT NULL default '0',
  `money` int(11) unsigned NOT NULL default '0',
  `str` smallint(4) unsigned NOT NULL default '0',
  `agi` smallint(4) unsigned NOT NULL default '0',
  `vit` smallint(4) unsigned NOT NULL default '0',
  `intel` smallint(4) unsigned NOT NULL default '0',
  `dex` smallint(4) unsigned NOT NULL default '0',
  `luk` smallint(4) unsigned NOT NULL default '0',
  `max_hp` varchar(30) NOT NULL default '0',
  `hp` varchar(30) NOT NULL default '0',
  `status_point` int(11) unsigned NOT NULL default '0',
  `hair` tinyint(4) unsigned NOT NULL default '0',
  `hair_color` smallint(5) unsigned NOT NULL default '0',
  `clothes_color` smallint(5) unsigned NOT NULL default '0',
  `gamemap` varchar(100) NOT NULL default '',
  `gamex` int(11) NOT NULL default '53',
  `gamey` int(11) NOT NULL default '111',
  `save_map` varchar(100) NOT NULL default '',
  `save_x` int(11) NOT NULL default '53',
  `save_y` int(11) NOT NULL default '111',
  `online` tinyint(2) NOT NULL default '0',
  `gender` ENUM('M','F','U') NOT NULL default 'U',
  PRIMARY KEY  (`characterid`),
  UNIQUE KEY `name_key` (`name`),
  KEY `account_id` (`account_id`),
  KEY `online` (`online`)
) ENGINE=MyISAM AUTO_INCREMENT=150000; 